logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

storage:
  bronze_path: "data/bronze"
  silver_path: "data/silver"
  gold_path: "data/gold"

dbt:
  project_dir: "dbt_project"

sources:
  entsoe:
    api_key: "${ENTSOE_API_KEY}"
    base_url: "https://web-api.tp.entsoe.eu/api"

    # --- Reusable Domain Placeholders ---
    primary_bidding_zone: "10YFR-RTE------C" # Great Britain
    interconnectors:
      FR: "10YFR-RTE------C"
      NL: "10YNL----------L"
      BE: "10YBE----------2"

    # --- List of specific data queries to run for this source ---
    queries:
      - name: "generation_per_type"
        documentType: "A75"
        # EXPLICIT: This query requires the 'outBiddingZone_Domain' parameter.
        domain_params:
          in_Domain: "${primary_bidding_zone}"
        params:
          processType: "A16"

      - name: "total_load"
        documentType: "A65"
        # EXPLICIT: This query also requires the 'outBiddingZone_Domain' parameter.
        domain_params:
          outBiddingZone_Domain: "${primary_bidding_zone}"
        params:
          processType: "A16"

      - name: "day_ahead_prices"
        documentType: "A44"
        # EXPLICIT: This query requires both 'in_Domain' and 'out_Domain'.
        domain_params:
          in_Domain: "${primary_bidding_zone}"
          out_Domain: "${primary_bidding_zone}"
        params: {}

  elexon:
      api_key: "${ELEXON_API_KEY}" # Will be loaded from your .env file
      base_url: "https://api.bmreports.com/BMRS"

      # --- List of specific reports to run for this source ---
      # Each report has a name, a BMRS report code, a version, and its required params
      reports:

        # Actual Aggregated Generation Per Type (AGPT / B1620)
        - name: "actual_aggregated_generation_per_type"
          code: "B1620"
          version: "v1"
          # This report uses a from/to date style
          date_param_type: "from_to_date"
          params: {}

        # Actual Total Load (B1610)
        - name: "actual_total_load"
          code: "B1610"
          version: "v1"
          # This report uses settlement date and period
          date_param_type: "settlement_date_period"
          params: {}
